### ISSUE TITLE
Badges toggle broken

### ISSUE THREAD

**Issue by mediaformat** [DigitalPygmalion/badge-factor#10]
Sur les pages de membres les badges n’apparaissent plus, et la fonction pour les faire apparaître ne fonctionne pas. 
Exemple : https://mysite.com/members/foo/ (il faut être connecté pour voir)

La fonction appelé par Ajax retourne toujours false
```
public function ajax_toggle_private_status()
    {
		$nonce = $_POST['nonce'];
		if ( ! wp_verify_nonce( $nonce, 'myajax-nonce' ) )
		{
			die();
		}

		$achievement_id = $_POST['achievement_id']; //<-Ceci ne retourne rien!
		$new_status = $GLOBALS['badgefactor']->toggle_private_status($achievement_id);

		$response = json_encode( array( 'success' => true, 'status' => $new_status) );
		header( "Content-Type: application/json" );
		echo $response;

		exit;
	}
```
` $_POST['achievement_id']` ne retourne rien!

**Comment by danidou** [comment]
There were problems in the Ajax script, the profile template AND the Badge Factor plugin, which were causing this toggle to malfunction.  All these problems have been fixed!
