### ISSUE TITLE
User achieved Badge urls

### ISSUE THREAD

**Issue by mediaformat** [DigitalPygmalion/badge-factor#11]
Attempting to view user badges at `http:/mysite.com/members/_foo_/badges/_bar_/`

Results in the following errors:

> Notice: Undefined variable: currentBadgeInfos in /WEB/sites/WP/web/app/themes/badge-factor-theme-integration/templates/page-header.php on line 87 
> Notice: Trying to get property of non-object in /WEB/sites/WP/web/app/themes/badge-factor-theme-integration/templates/page-header.php on line 87

**Description**

> [badgeos_achievements_list type="all" limit="10" orderby="menu_order" order="ASC" wpms="false"]
> (with a list of posts)

**Issued on**

> Notice: Trying to get property of non-object in /WEB/sites/WP/web/app/plugins/badge-factor/templates/single-badges.php on line 40 24 juillet 2017

The only currently working badge url form is : 
`http:/mysite.com/?badges=bar&member=foo`

This url type is referenced in `display_certificate()` function of [badge-factor-certificates](https://github.com/DigitalPygmalion/badge-factor-certificates/blob/develop/badge-factor-certificates.php)

**Comment by danidou** [comment]
The URI format /members/_foo_/badges/_bar_/ has been fixed and tested successfully. The template-profile buddypress template has been modified to use this format, in order for a member's page to link to this member's badges properly.

**Comment by audiovisuel-uqam** [comment]
> The URI format /members/foo/badges/bar/ has been fixed and tested successfully. 

The Page returns a _Page not found_ header.

Additionally the following errors are displayed:
`Notice: Undefined offset: 0 in /web/app/plugins/badge-factor/badgefactor.php on line 1348`

Erreur de la base de données WordPress : [Table 'Badges-WP.wp_rg_lead_detail' doesn't exist]
`SELECT pdf.form_id AS form_id, pdfm.display_meta AS form_meta, pdf.lead_id AS lead_id FROM wp_rg_lead_detail AS pdf INNER JOIN wp_postmeta AS pm ON pdf.value = pm.meta_value INNER JOIN wp_posts AS p ON p.ID = pm.post_id INNER JOIN wp_rg_form_meta AS pdfm ON pdf.form_id = pdfm.form_id WHERE p.post_status = 'publish' AND pm.meta_key = '_badgeos_submission_achievement_id' AND pm.post_id = '1400'`
This latter error suggests that `$proof = $GLOBALS['badgefactor']->get_proof($submission->ID);` is still relying on gravity forms, and not [badge-factor-certificates](https://github.com/DigitalPygmalion/badge-factor-certificates)
