### ISSUE TITLE
Badges no longer display

### ISSUE THREAD

**Issue by mediaformat** [DigitalPygmalion/badge-factor#12]
Since [refactor](https://github.com/DigitalPygmalion/badge-factor/commit/4a6deec6fa17c5cabae72e08a61affde6085b016) of `get_user_achievements()`
The [badge-factor-theme/buddypress/members/template-profile.php](https://github.com/DigitalPygmalion/badge-factor-theme/issues/1) can not display badges/achievements

**Comment by audiovisuel-uqam** [comment]
actually the problem seems upstream, where `$achievement->badge_id` **badge_id** does not correspond to anything.
Replacing with `$achievement->ID`, seems to solve the issue

**Comment by audiovisuel-uqam** [comment]
ok, not working anymore... :(
`get_user_achievements()` returns, non-badge post

**Comment by audiovisuel-uqam** [comment]
Working again, without intervention.

I can only assume the following is responsable for the inconsistent results:
```
//store our resulting WP_Query object in a transient for one hour.
set_transient( 'custom_badgeos_user_achievements', $badges, 60*60 );
```

**Comment by danidou** [comment]
This indeed seems to have been the culprit. It has been removed, and badges are once again displaying.
